///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// Your custom recording code should go in this file.
// The designer will only add methods to this file, so your custom code won't be overwritten.
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace Ranorex_POC.TestCases.WordTC
{
    public partial class TC101_ValidateIconInTheRibbon
    {
        /// <summary>
        /// This method gets called right after the recording has been started.
        /// It can be used to execute recording specific initialization code.
        /// </summary>
        private void Init()
        {
            // Your recording specific initialization code goes here.
        }

        public void OpenNewDoc()
        {
        	Word.WordMethods.OpenWord();
        }

        public void GoToInsertRibbon()
        {
        	Word.WordMethods.Click_InsertMenuButton();
        }

        public void GoToHomeRibbon()
        {
            Word.WordMethods.Click_HomeMenuButton();
        }

        public void CloseDoc()
        {
            Word.WordMethods.Click_CloseDocumentAndDoNotSave();
        }

        public void Validate_InsertPictureIcon()
        {
        	Word.WordValidation.ValidateInsertPictureIconExists();
        }

    }
}
