///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// Your custom recording code should go in this file.
// The designer will only add methods to this file, so your custom code won't be overwritten.
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace Ranorex_POC.TestCases.WordTC
{
    public partial class TC103_ValidateTag
    {
        /// <summary>
        /// This method gets called right after the recording has been started.
        /// It can be used to execute recording specific initialization code.
        /// </summary>
        private void Init()
        {
            // Your recording specific initialization code goes here.
        }

        public void CloseDocument()
        {
            Word.WordMethods.Click_CloseDocumentAndDoNotSave();
        }

        public void ValidateTag()
        {
        	Word.WordValidation.ValidateTagExists("Confidential");
        }

        public void OpenDoc()
        {
        	string path = Common.CommonMethods.ReturnStringPath("\\Files\\TC003.docx");
        	Report.Info(path);
        	Common.OpeningApps.OpenApplication(path);
        }

        public void GoToInfoSession()
        {
        	Word.WordMethods.Click_FileMenuButton();
        	Word.WordMethods.Click_InfoLeftMenuButton();
        }

        public void GoToHome()
        {
            Word.WordMethods.Click_BackLeftMenuButton();
        }

    }
}
