///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace Ranorex_POC.TestCases.WordTC
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The TC101_ValidateIconInTheRibbon recording.
    /// </summary>
    [TestModule("498f7d83-47fe-453c-9202-68d22ff0548c", ModuleType.Recording, 1)]
    public partial class TC101_ValidateIconInTheRibbon : ITestModule
    {
        /// <summary>
        /// Holds an instance of the global::Ranorex_POC.Ranorex_POCRepository repository.
        /// </summary>
        public static global::Ranorex_POC.Ranorex_POCRepository repo = global::Ranorex_POC.Ranorex_POCRepository.Instance;

        static TC101_ValidateIconInTheRibbon instance = new TC101_ValidateIconInTheRibbon();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public TC101_ValidateIconInTheRibbon()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static TC101_ValidateIconInTheRibbon Instance
        {
            get { return instance; }
        }

#region Variables

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 20;
            Delay.SpeedFactor = 1.00;

            Init();

            OpenNewDoc();
            Delay.Milliseconds(0);
            
            GoToInsertRibbon();
            Delay.Milliseconds(0);
            
            Validate_InsertPictureIcon();
            Delay.Milliseconds(0);
            
            GoToHomeRibbon();
            Delay.Milliseconds(0);
            
            CloseDoc();
            Delay.Milliseconds(0);
            
        }

#region Image Feature Data
        /// <summary>
        /// DO NOT REFERENCE THIS CODE  - auto generated
        /// </summary>
        CompressedImage InsertPictureIcon_Screenshot1
        { get { return repo.Word.Ribbon.InsertPictureIconInfo.GetScreenshot1(new Rectangle(0, 0, 47, 69)); } }

        /// <summary>
        /// DO NOT REFERENCE THIS CODE  - auto generated
        /// </summary>
        Imaging.FindOptions InsertPictureIcon_Screenshot1_Options
        { get { return Imaging.FindOptions.Default; } }

#endregion
    }
#pragma warning restore 0436
}
