///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// Your custom recording code should go in this file.
// The designer will only add methods to this file, so your custom code won't be overwritten.
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace Ranorex_POC.TestCases.OutlookTC
{
    public partial class TC003_ValidateEmailRecipient
    {
        /// <summary>
        /// This method gets called right after the recording has been started.
        /// It can be used to execute recording specific initialization code.
        /// </summary>
        private void Init()
        {
            // Your recording specific initialization code goes here.
        }

        public void GoToInbox()
        {
        	Outlook.OutlookMethods.Click_InBoxFolder();
        }

        public void SendEmail()
        {
        	// To make this test works in other environments, it is required to change the email for this test
        	Outlook.MessageMethods.SendNewEmail("Test 003", "Email body 003","alberto.hirota@autdom1.local;john.brown@autdom1.local");
        }

        public void ValidateEmailRecipient()
        {
        	Outlook.OutlookValidation.EmailRecipientExists("John Brown");
        }

        public void SelectEmail()
        {
        	Outlook.OutlookMethods.ClickEmailReceived("Test 003");
        }

    }
}
