///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Drawing;
using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace Ranorex_POC
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    /// The class representing the Ranorex_POCRepository element repository.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
    [RepositoryFolder("0415c4b0-18fc-4aa6-9972-68e7f0d3bb83")]
    public partial class Ranorex_POCRepository : RepoGenBaseFolder
    {
        static Ranorex_POCRepository instance = new Ranorex_POCRepository();
        Ranorex_POCRepositoryFolders.ExplorerAppFolder _explorer;
        Ranorex_POCRepositoryFolders.RunAppFolder _run;
        Ranorex_POCRepositoryFolders.OutlookAppFolder _outlook;

        /// <summary>
        /// Gets the singleton class instance representing the Ranorex_POCRepository element repository.
        /// </summary>
        [RepositoryFolder("0415c4b0-18fc-4aa6-9972-68e7f0d3bb83")]
        public static Ranorex_POCRepository Instance
        {
            get { return instance; }
        }

        /// <summary>
        /// Repository class constructor.
        /// </summary>
        public Ranorex_POCRepository() 
            : base("Ranorex_POCRepository", "/", null, 0, false, "0415c4b0-18fc-4aa6-9972-68e7f0d3bb83", ".\\RepositoryImages\\Ranorex_POCRepository0415c4b0.rximgres")
        {
            _explorer = new Ranorex_POCRepositoryFolders.ExplorerAppFolder(this);
            _run = new Ranorex_POCRepositoryFolders.RunAppFolder(this);
            _outlook = new Ranorex_POCRepositoryFolders.OutlookAppFolder(this);
        }

#region Variables

#endregion

        /// <summary>
        /// The Self item info.
        /// </summary>
        [RepositoryItemInfo("0415c4b0-18fc-4aa6-9972-68e7f0d3bb83")]
        public virtual RepoItemInfo SelfInfo
        {
            get
            {
                return _selfInfo;
            }
        }

        /// <summary>
        /// The Explorer folder.
        /// </summary>
        [RepositoryFolder("996aeea8-e823-487b-bc09-e5587540f8f4")]
        public virtual Ranorex_POCRepositoryFolders.ExplorerAppFolder Explorer
        {
            get { return _explorer; }
        }

        /// <summary>
        /// The Run folder.
        /// </summary>
        [RepositoryFolder("1de98707-09f7-4cda-b595-7f3da6e79405")]
        public virtual Ranorex_POCRepositoryFolders.RunAppFolder Run
        {
            get { return _run; }
        }

        /// <summary>
        /// The Outlook folder.
        /// </summary>
        [RepositoryFolder("ecddf4b2-00ba-4aca-89f6-2ee215eca9f9")]
        public virtual Ranorex_POCRepositoryFolders.OutlookAppFolder Outlook
        {
            get { return _outlook; }
        }
    }

    /// <summary>
    /// Inner folder classes.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
    public partial class Ranorex_POCRepositoryFolders
    {
        /// <summary>
        /// The ExplorerAppFolder folder.
        /// </summary>
        [RepositoryFolder("996aeea8-e823-487b-bc09-e5587540f8f4")]
        public partial class ExplorerAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _taskbarInfo;

            /// <summary>
            /// Creates a new Explorer  folder.
            /// </summary>
            public ExplorerAppFolder(RepoGenBaseFolder parentFolder) :
                    base("Explorer", "//", parentFolder, 5000, null, false, "996aeea8-e823-487b-bc09-e5587540f8f4", "")
            {
                _taskbarInfo = new RepoItemInfo(this, "TaskBar", "menubar[@processname='explorer']", "element", 10000, null, "e40fe195-1edc-4d72-9a8d-a22575ade190");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("996aeea8-e823-487b-bc09-e5587540f8f4")]
            public virtual Ranorex.Unknown Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Unknown>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("996aeea8-e823-487b-bc09-e5587540f8f4")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The TaskBar item.
            /// </summary>
            [RepositoryItem("e40fe195-1edc-4d72-9a8d-a22575ade190")]
            public virtual Ranorex.MenuBar TaskBar
            {
                get
                {
                    return _taskbarInfo.CreateAdapter<Ranorex.MenuBar>(true);
                }
            }

            /// <summary>
            /// The TaskBar item info.
            /// </summary>
            [RepositoryItemInfo("e40fe195-1edc-4d72-9a8d-a22575ade190")]
            public virtual RepoItemInfo TaskBarInfo
            {
                get
                {
                    return _taskbarInfo;
                }
            }
        }

        /// <summary>
        /// The RunAppFolder folder.
        /// </summary>
        [RepositoryFolder("1de98707-09f7-4cda-b595-7f3da6e79405")]
        public partial class RunAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _opentextInfo;
            RepoItemInfo _buttonokInfo;

            /// <summary>
            /// Creates a new Run  folder.
            /// </summary>
            public RunAppFolder(RepoGenBaseFolder parentFolder) :
                    base("Run", "/form[@title='Run']", parentFolder, 30000, null, false, "1de98707-09f7-4cda-b595-7f3da6e79405", "")
            {
                _opentextInfo = new RepoItemInfo(this, "OpenText", "combobox/text[@controlid='1001']", "element", 30000, null, "1e99ff01-de51-41b0-80ca-ac7fb62a911f");
                _buttonokInfo = new RepoItemInfo(this, "ButtonOk", "button[@text='OK']", "element", 30000, null, "3ae2ce2d-38f0-4352-be4c-992d29b735a2");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("1de98707-09f7-4cda-b595-7f3da6e79405")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("1de98707-09f7-4cda-b595-7f3da6e79405")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The OpenText item.
            /// </summary>
            [RepositoryItem("1e99ff01-de51-41b0-80ca-ac7fb62a911f")]
            public virtual Ranorex.Text OpenText
            {
                get
                {
                    return _opentextInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The OpenText item info.
            /// </summary>
            [RepositoryItemInfo("1e99ff01-de51-41b0-80ca-ac7fb62a911f")]
            public virtual RepoItemInfo OpenTextInfo
            {
                get
                {
                    return _opentextInfo;
                }
            }

            /// <summary>
            /// The ButtonOk item.
            /// </summary>
            [RepositoryItem("3ae2ce2d-38f0-4352-be4c-992d29b735a2")]
            public virtual Ranorex.Button ButtonOk
            {
                get
                {
                    return _buttonokInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The ButtonOk item info.
            /// </summary>
            [RepositoryItemInfo("3ae2ce2d-38f0-4352-be4c-992d29b735a2")]
            public virtual RepoItemInfo ButtonOkInfo
            {
                get
                {
                    return _buttonokInfo;
                }
            }
        }

        /// <summary>
        /// The OutlookAppFolder folder.
        /// </summary>
        [RepositoryFolder("ecddf4b2-00ba-4aca-89f6-2ee215eca9f9")]
        public partial class OutlookAppFolder : RepoGenBaseFolder
        {
            Ranorex_POCRepositoryFolders.MailFoldersFolder _mailfolders;
            RepoItemInfo _deleteallInfo;
            RepoItemInfo _buttonyesInfo;

            /// <summary>
            /// Creates a new Outlook  folder.
            /// </summary>
            public OutlookAppFolder(RepoGenBaseFolder parentFolder) :
                    base("Outlook", "/form[@processname='OUTLOOK']", parentFolder, 30000, null, false, "ecddf4b2-00ba-4aca-89f6-2ee215eca9f9", "")
            {
                _mailfolders = new Ranorex_POCRepositoryFolders.MailFoldersFolder(this);
                _deleteallInfo = new RepoItemInfo(this, "DeleteAll", ".//menuitem[@name='Delete All']", "element", 30000, null, "c20ebfa9-5313-4814-89b4-0472cf786a9a");
                _buttonyesInfo = new RepoItemInfo(this, "ButtonYes", ".//button[@text='&Yes']", "element", 30000, null, "8917619b-c58c-4447-ba9d-fbb051873262");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("ecddf4b2-00ba-4aca-89f6-2ee215eca9f9")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("ecddf4b2-00ba-4aca-89f6-2ee215eca9f9")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The DeleteAll item.
            /// </summary>
            [RepositoryItem("c20ebfa9-5313-4814-89b4-0472cf786a9a")]
            public virtual Ranorex.MenuItem DeleteAll
            {
                get
                {
                    return _deleteallInfo.CreateAdapter<Ranorex.MenuItem>(true);
                }
            }

            /// <summary>
            /// The DeleteAll item info.
            /// </summary>
            [RepositoryItemInfo("c20ebfa9-5313-4814-89b4-0472cf786a9a")]
            public virtual RepoItemInfo DeleteAllInfo
            {
                get
                {
                    return _deleteallInfo;
                }
            }

            /// <summary>
            /// The ButtonYes item.
            /// </summary>
            [RepositoryItem("8917619b-c58c-4447-ba9d-fbb051873262")]
            public virtual Ranorex.Button ButtonYes
            {
                get
                {
                    return _buttonyesInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The ButtonYes item info.
            /// </summary>
            [RepositoryItemInfo("8917619b-c58c-4447-ba9d-fbb051873262")]
            public virtual RepoItemInfo ButtonYesInfo
            {
                get
                {
                    return _buttonyesInfo;
                }
            }

            /// <summary>
            /// The MailFolders folder.
            /// </summary>
            [RepositoryFolder("a8b73004-1c47-41c6-a3e2-2a498e69d851")]
            public virtual Ranorex_POCRepositoryFolders.MailFoldersFolder MailFolders
            {
                get { return _mailfolders; }
            }
        }

        /// <summary>
        /// The MailFoldersFolder folder.
        /// </summary>
        [RepositoryFolder("a8b73004-1c47-41c6-a3e2-2a498e69d851")]
        public partial class MailFoldersFolder : RepoGenBaseFolder
        {
            RepoItemInfo _inboxfolderInfo;
            RepoItemInfo _draftfolderInfo;

            /// <summary>
            /// Creates a new MailFolders  folder.
            /// </summary>
            public MailFoldersFolder(RepoGenBaseFolder parentFolder) :
                    base("MailFolders", ".//tree[@name='Mail Folders']", parentFolder, 30000, null, false, "a8b73004-1c47-41c6-a3e2-2a498e69d851", "")
            {
                _inboxfolderInfo = new RepoItemInfo(this, "InboxFolder", ".//treeitem[@name>'Inbox']", "element", 30000, null, "b2271db4-98aa-41ab-aed1-e0aa60fc280f");
                _draftfolderInfo = new RepoItemInfo(this, "DraftFolder", ".//treeitem[@name>'Draft']", "element", 30000, null, "78e1b64b-550c-472b-ae36-157adde53a36");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("a8b73004-1c47-41c6-a3e2-2a498e69d851")]
            public virtual Ranorex.Tree Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Tree>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("a8b73004-1c47-41c6-a3e2-2a498e69d851")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The InboxFolder item.
            /// </summary>
            [RepositoryItem("b2271db4-98aa-41ab-aed1-e0aa60fc280f")]
            public virtual Ranorex.TreeItem InboxFolder
            {
                get
                {
                    return _inboxfolderInfo.CreateAdapter<Ranorex.TreeItem>(true);
                }
            }

            /// <summary>
            /// The InboxFolder item info.
            /// </summary>
            [RepositoryItemInfo("b2271db4-98aa-41ab-aed1-e0aa60fc280f")]
            public virtual RepoItemInfo InboxFolderInfo
            {
                get
                {
                    return _inboxfolderInfo;
                }
            }

            /// <summary>
            /// The DraftFolder item.
            /// </summary>
            [RepositoryItem("78e1b64b-550c-472b-ae36-157adde53a36")]
            public virtual Ranorex.TreeItem DraftFolder
            {
                get
                {
                    return _draftfolderInfo.CreateAdapter<Ranorex.TreeItem>(true);
                }
            }

            /// <summary>
            /// The DraftFolder item info.
            /// </summary>
            [RepositoryItemInfo("78e1b64b-550c-472b-ae36-157adde53a36")]
            public virtual RepoItemInfo DraftFolderInfo
            {
                get
                {
                    return _draftfolderInfo;
                }
            }
        }

    }
#pragma warning restore 0436
}
