///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Drawing;
using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace Ranorex_POC
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    /// The class representing the Ranorex_POCRepository element repository.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
    [RepositoryFolder("0415c4b0-18fc-4aa6-9972-68e7f0d3bb83")]
    public partial class Ranorex_POCRepository : RepoGenBaseFolder
    {
        static Ranorex_POCRepository instance = new Ranorex_POCRepository();
        Ranorex_POCRepositoryFolders.ExplorerAppFolder _explorer;
        Ranorex_POCRepositoryFolders.RunAppFolder _run;
        Ranorex_POCRepositoryFolders.OutlookAppFolder _outlook;
        Ranorex_POCRepositoryFolders.OutlookMessageAppFolder _outlookmessage;
        Ranorex_POCRepositoryFolders.OfficeWarnAppFolder _officewarn;
        Ranorex_POCRepositoryFolders.WordAppFolder _word;

        /// <summary>
        /// Gets the singleton class instance representing the Ranorex_POCRepository element repository.
        /// </summary>
        [RepositoryFolder("0415c4b0-18fc-4aa6-9972-68e7f0d3bb83")]
        public static Ranorex_POCRepository Instance
        {
            get { return instance; }
        }

        /// <summary>
        /// Repository class constructor.
        /// </summary>
        public Ranorex_POCRepository() 
            : base("Ranorex_POCRepository", "/", null, 0, false, "0415c4b0-18fc-4aa6-9972-68e7f0d3bb83", ".\\RepositoryImages\\Ranorex_POCRepository0415c4b0.rximgres")
        {
            _explorer = new Ranorex_POCRepositoryFolders.ExplorerAppFolder(this);
            _run = new Ranorex_POCRepositoryFolders.RunAppFolder(this);
            _outlook = new Ranorex_POCRepositoryFolders.OutlookAppFolder(this);
            _outlookmessage = new Ranorex_POCRepositoryFolders.OutlookMessageAppFolder(this);
            _officewarn = new Ranorex_POCRepositoryFolders.OfficeWarnAppFolder(this);
            _word = new Ranorex_POCRepositoryFolders.WordAppFolder(this);
        }

#region Variables

        string _EmailSubject = "";

        /// <summary>
        /// Gets or sets the value of variable EmailSubject.
        /// </summary>
        [TestVariable("6939149d-f841-4d99-98ed-994a06697567")]
        public string EmailSubject
        {
            get { return _EmailSubject; }
            set { _EmailSubject = value; }
        }

#endregion

        /// <summary>
        /// The Self item info.
        /// </summary>
        [RepositoryItemInfo("0415c4b0-18fc-4aa6-9972-68e7f0d3bb83")]
        public virtual RepoItemInfo SelfInfo
        {
            get
            {
                return _selfInfo;
            }
        }

        /// <summary>
        /// The Explorer folder.
        /// </summary>
        [RepositoryFolder("996aeea8-e823-487b-bc09-e5587540f8f4")]
        public virtual Ranorex_POCRepositoryFolders.ExplorerAppFolder Explorer
        {
            get { return _explorer; }
        }

        /// <summary>
        /// The Run folder.
        /// </summary>
        [RepositoryFolder("1de98707-09f7-4cda-b595-7f3da6e79405")]
        public virtual Ranorex_POCRepositoryFolders.RunAppFolder Run
        {
            get { return _run; }
        }

        /// <summary>
        /// The Outlook folder.
        /// </summary>
        [RepositoryFolder("ecddf4b2-00ba-4aca-89f6-2ee215eca9f9")]
        public virtual Ranorex_POCRepositoryFolders.OutlookAppFolder Outlook
        {
            get { return _outlook; }
        }

        /// <summary>
        /// The OutlookMessage folder.
        /// </summary>
        [RepositoryFolder("031a66a7-dbdb-4e60-ba7f-9982de8983d6")]
        public virtual Ranorex_POCRepositoryFolders.OutlookMessageAppFolder OutlookMessage
        {
            get { return _outlookmessage; }
        }

        /// <summary>
        /// The OfficeWarn folder.
        /// </summary>
        [RepositoryFolder("d6f30d71-e034-4abd-a833-0ac2242cdbd4")]
        public virtual Ranorex_POCRepositoryFolders.OfficeWarnAppFolder OfficeWarn
        {
            get { return _officewarn; }
        }

        /// <summary>
        /// The Word folder.
        /// </summary>
        [RepositoryFolder("9268ee68-afc1-4d23-b5e3-2ad953440325")]
        public virtual Ranorex_POCRepositoryFolders.WordAppFolder Word
        {
            get { return _word; }
        }
    }

    /// <summary>
    /// Inner folder classes.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
    public partial class Ranorex_POCRepositoryFolders
    {
        /// <summary>
        /// The ExplorerAppFolder folder.
        /// </summary>
        [RepositoryFolder("996aeea8-e823-487b-bc09-e5587540f8f4")]
        public partial class ExplorerAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _taskbarInfo;

            /// <summary>
            /// Creates a new Explorer  folder.
            /// </summary>
            public ExplorerAppFolder(RepoGenBaseFolder parentFolder) :
                    base("Explorer", "//", parentFolder, 5000, null, false, "996aeea8-e823-487b-bc09-e5587540f8f4", "")
            {
                _taskbarInfo = new RepoItemInfo(this, "TaskBar", "menubar[@processname='explorer']", "element", 10000, null, "e40fe195-1edc-4d72-9a8d-a22575ade190");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("996aeea8-e823-487b-bc09-e5587540f8f4")]
            public virtual Ranorex.Unknown Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Unknown>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("996aeea8-e823-487b-bc09-e5587540f8f4")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The TaskBar item.
            /// </summary>
            [RepositoryItem("e40fe195-1edc-4d72-9a8d-a22575ade190")]
            public virtual Ranorex.MenuBar TaskBar
            {
                get
                {
                    return _taskbarInfo.CreateAdapter<Ranorex.MenuBar>(true);
                }
            }

            /// <summary>
            /// The TaskBar item info.
            /// </summary>
            [RepositoryItemInfo("e40fe195-1edc-4d72-9a8d-a22575ade190")]
            public virtual RepoItemInfo TaskBarInfo
            {
                get
                {
                    return _taskbarInfo;
                }
            }
        }

        /// <summary>
        /// The RunAppFolder folder.
        /// </summary>
        [RepositoryFolder("1de98707-09f7-4cda-b595-7f3da6e79405")]
        public partial class RunAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _opentextInfo;
            RepoItemInfo _buttonokInfo;

            /// <summary>
            /// Creates a new Run  folder.
            /// </summary>
            public RunAppFolder(RepoGenBaseFolder parentFolder) :
                    base("Run", "/form[@title='Run']", parentFolder, 30000, null, false, "1de98707-09f7-4cda-b595-7f3da6e79405", "")
            {
                _opentextInfo = new RepoItemInfo(this, "OpenText", "combobox/text[@controlid='1001']", "element", 30000, null, "1e99ff01-de51-41b0-80ca-ac7fb62a911f");
                _buttonokInfo = new RepoItemInfo(this, "ButtonOk", "button[@text='OK']", "element", 30000, null, "3ae2ce2d-38f0-4352-be4c-992d29b735a2");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("1de98707-09f7-4cda-b595-7f3da6e79405")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("1de98707-09f7-4cda-b595-7f3da6e79405")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The OpenText item.
            /// </summary>
            [RepositoryItem("1e99ff01-de51-41b0-80ca-ac7fb62a911f")]
            public virtual Ranorex.Text OpenText
            {
                get
                {
                    return _opentextInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The OpenText item info.
            /// </summary>
            [RepositoryItemInfo("1e99ff01-de51-41b0-80ca-ac7fb62a911f")]
            public virtual RepoItemInfo OpenTextInfo
            {
                get
                {
                    return _opentextInfo;
                }
            }

            /// <summary>
            /// The ButtonOk item.
            /// </summary>
            [RepositoryItem("3ae2ce2d-38f0-4352-be4c-992d29b735a2")]
            public virtual Ranorex.Button ButtonOk
            {
                get
                {
                    return _buttonokInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The ButtonOk item info.
            /// </summary>
            [RepositoryItemInfo("3ae2ce2d-38f0-4352-be4c-992d29b735a2")]
            public virtual RepoItemInfo ButtonOkInfo
            {
                get
                {
                    return _buttonokInfo;
                }
            }
        }

        /// <summary>
        /// The OutlookAppFolder folder.
        /// </summary>
        [RepositoryFolder("ecddf4b2-00ba-4aca-89f6-2ee215eca9f9")]
        public partial class OutlookAppFolder : RepoGenBaseFolder
        {
            Ranorex_POCRepositoryFolders.MailFoldersFolder _mailfolders;
            Ranorex_POCRepositoryFolders.EmailListFolder _emaillist;
            Ranorex_POCRepositoryFolders.MenuButtonBarFolder _menubuttonbar;
            Ranorex_POCRepositoryFolders.EmailBottomViewFolder _emailbottomview;
            Ranorex_POCRepositoryFolders.RibbonFolder _ribbon;
            RepoItemInfo _deleteallInfo;
            RepoItemInfo _buttonyesInfo;
            RepoItemInfo _buttonmaximizeInfo;

            /// <summary>
            /// Creates a new Outlook  folder.
            /// </summary>
            public OutlookAppFolder(RepoGenBaseFolder parentFolder) :
                    base("Outlook", "/form[@processname='OUTLOOK']", parentFolder, 30000, null, false, "ecddf4b2-00ba-4aca-89f6-2ee215eca9f9", "")
            {
                _mailfolders = new Ranorex_POCRepositoryFolders.MailFoldersFolder(this);
                _emaillist = new Ranorex_POCRepositoryFolders.EmailListFolder(this);
                _menubuttonbar = new Ranorex_POCRepositoryFolders.MenuButtonBarFolder(this);
                _emailbottomview = new Ranorex_POCRepositoryFolders.EmailBottomViewFolder(this);
                _ribbon = new Ranorex_POCRepositoryFolders.RibbonFolder(this);
                _deleteallInfo = new RepoItemInfo(this, "DeleteAll", ".//menuitem[@name='Delete All']", "element", 30000, null, "c20ebfa9-5313-4814-89b4-0472cf786a9a");
                _buttonyesInfo = new RepoItemInfo(this, "ButtonYes", ".//button[@text='&Yes']", "element", 30000, null, "8917619b-c58c-4447-ba9d-fbb051873262");
                _buttonmaximizeInfo = new RepoItemInfo(this, "ButtonMaximize", ".//container[@name='Ribbon']/button[@name='Maximize']", "element", 30000, null, "a6659051-e168-4173-9d10-3336cc962946");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("ecddf4b2-00ba-4aca-89f6-2ee215eca9f9")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("ecddf4b2-00ba-4aca-89f6-2ee215eca9f9")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The DeleteAll item.
            /// </summary>
            [RepositoryItem("c20ebfa9-5313-4814-89b4-0472cf786a9a")]
            public virtual Ranorex.MenuItem DeleteAll
            {
                get
                {
                    return _deleteallInfo.CreateAdapter<Ranorex.MenuItem>(true);
                }
            }

            /// <summary>
            /// The DeleteAll item info.
            /// </summary>
            [RepositoryItemInfo("c20ebfa9-5313-4814-89b4-0472cf786a9a")]
            public virtual RepoItemInfo DeleteAllInfo
            {
                get
                {
                    return _deleteallInfo;
                }
            }

            /// <summary>
            /// The ButtonYes item.
            /// </summary>
            [RepositoryItem("8917619b-c58c-4447-ba9d-fbb051873262")]
            public virtual Ranorex.Button ButtonYes
            {
                get
                {
                    return _buttonyesInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The ButtonYes item info.
            /// </summary>
            [RepositoryItemInfo("8917619b-c58c-4447-ba9d-fbb051873262")]
            public virtual RepoItemInfo ButtonYesInfo
            {
                get
                {
                    return _buttonyesInfo;
                }
            }

            /// <summary>
            /// The ButtonMaximize item.
            /// </summary>
            [RepositoryItem("a6659051-e168-4173-9d10-3336cc962946")]
            public virtual Ranorex.Button ButtonMaximize
            {
                get
                {
                    return _buttonmaximizeInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The ButtonMaximize item info.
            /// </summary>
            [RepositoryItemInfo("a6659051-e168-4173-9d10-3336cc962946")]
            public virtual RepoItemInfo ButtonMaximizeInfo
            {
                get
                {
                    return _buttonmaximizeInfo;
                }
            }

            /// <summary>
            /// The MailFolders folder.
            /// </summary>
            [RepositoryFolder("a8b73004-1c47-41c6-a3e2-2a498e69d851")]
            public virtual Ranorex_POCRepositoryFolders.MailFoldersFolder MailFolders
            {
                get { return _mailfolders; }
            }

            /// <summary>
            /// The EmailList folder.
            /// </summary>
            [RepositoryFolder("bc453254-76aa-48c2-9bfd-05b4ec93a193")]
            public virtual Ranorex_POCRepositoryFolders.EmailListFolder EmailList
            {
                get { return _emaillist; }
            }

            /// <summary>
            /// The MenuButtonBar folder.
            /// </summary>
            [RepositoryFolder("43b586d2-d8da-4a3f-87f2-9e22624fca6b")]
            public virtual Ranorex_POCRepositoryFolders.MenuButtonBarFolder MenuButtonBar
            {
                get { return _menubuttonbar; }
            }

            /// <summary>
            /// The EmailBottomView folder.
            /// </summary>
            [RepositoryFolder("40412a66-951f-4383-a26b-f700ea829aec")]
            public virtual Ranorex_POCRepositoryFolders.EmailBottomViewFolder EmailBottomView
            {
                get { return _emailbottomview; }
            }

            /// <summary>
            /// The Ribbon folder.
            /// </summary>
            [RepositoryFolder("7bd30b78-158e-4f4a-a099-e1a136a02c72")]
            public virtual Ranorex_POCRepositoryFolders.RibbonFolder Ribbon
            {
                get { return _ribbon; }
            }
        }

        /// <summary>
        /// The MailFoldersFolder folder.
        /// </summary>
        [RepositoryFolder("a8b73004-1c47-41c6-a3e2-2a498e69d851")]
        public partial class MailFoldersFolder : RepoGenBaseFolder
        {
            RepoItemInfo _inboxfolderInfo;
            RepoItemInfo _draftfolderInfo;

            /// <summary>
            /// Creates a new MailFolders  folder.
            /// </summary>
            public MailFoldersFolder(RepoGenBaseFolder parentFolder) :
                    base("MailFolders", ".//tree[@name='Mail Folders']", parentFolder, 30000, null, false, "a8b73004-1c47-41c6-a3e2-2a498e69d851", "")
            {
                _inboxfolderInfo = new RepoItemInfo(this, "InboxFolder", ".//treeitem[@name>'Inbox']", "element", 30000, null, "b2271db4-98aa-41ab-aed1-e0aa60fc280f");
                _draftfolderInfo = new RepoItemInfo(this, "DraftFolder", ".//treeitem[@name>'Draft']", "element", 30000, null, "78e1b64b-550c-472b-ae36-157adde53a36");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("a8b73004-1c47-41c6-a3e2-2a498e69d851")]
            public virtual Ranorex.Tree Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Tree>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("a8b73004-1c47-41c6-a3e2-2a498e69d851")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The InboxFolder item.
            /// </summary>
            [RepositoryItem("b2271db4-98aa-41ab-aed1-e0aa60fc280f")]
            public virtual Ranorex.TreeItem InboxFolder
            {
                get
                {
                    return _inboxfolderInfo.CreateAdapter<Ranorex.TreeItem>(true);
                }
            }

            /// <summary>
            /// The InboxFolder item info.
            /// </summary>
            [RepositoryItemInfo("b2271db4-98aa-41ab-aed1-e0aa60fc280f")]
            public virtual RepoItemInfo InboxFolderInfo
            {
                get
                {
                    return _inboxfolderInfo;
                }
            }

            /// <summary>
            /// The DraftFolder item.
            /// </summary>
            [RepositoryItem("78e1b64b-550c-472b-ae36-157adde53a36")]
            public virtual Ranorex.TreeItem DraftFolder
            {
                get
                {
                    return _draftfolderInfo.CreateAdapter<Ranorex.TreeItem>(true);
                }
            }

            /// <summary>
            /// The DraftFolder item info.
            /// </summary>
            [RepositoryItemInfo("78e1b64b-550c-472b-ae36-157adde53a36")]
            public virtual RepoItemInfo DraftFolderInfo
            {
                get
                {
                    return _draftfolderInfo;
                }
            }
        }

        /// <summary>
        /// The EmailListFolder folder.
        /// </summary>
        [RepositoryFolder("bc453254-76aa-48c2-9bfd-05b4ec93a193")]
        public partial class EmailListFolder : RepoGenBaseFolder
        {
            RepoItemInfo _emailsubjectInfo;
            RepoItemInfo _groupbyInfo;

            /// <summary>
            /// Creates a new EmailList  folder.
            /// </summary>
            public EmailListFolder(RepoGenBaseFolder parentFolder) :
                    base("EmailList", ".//element[@automationid='4704']//.//container[@name~'Group By: ']", parentFolder, 30000, null, false, "bc453254-76aa-48c2-9bfd-05b4ec93a193", "")
            {
                _emailsubjectInfo = new RepoItemInfo(this, "EmailSubject", ".//text[@caption=$EmailSubject]", "", 30000, null, "f83f8b32-acc5-4ff9-8889-68cd515d824e");
                _groupbyInfo = new RepoItemInfo(this, "GroupBy", ".//container[@name~'Group By: ']", "", 30000, null, "6e642d51-611e-4be6-9e85-947e1fe91d92");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("bc453254-76aa-48c2-9bfd-05b4ec93a193")]
            public virtual Ranorex.Container Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Container>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("bc453254-76aa-48c2-9bfd-05b4ec93a193")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The EmailSubject item.
            /// </summary>
            [RepositoryItem("f83f8b32-acc5-4ff9-8889-68cd515d824e")]
            public virtual Ranorex.Text EmailSubject
            {
                get
                {
                    return _emailsubjectInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The EmailSubject item info.
            /// </summary>
            [RepositoryItemInfo("f83f8b32-acc5-4ff9-8889-68cd515d824e")]
            public virtual RepoItemInfo EmailSubjectInfo
            {
                get
                {
                    return _emailsubjectInfo;
                }
            }

            /// <summary>
            /// The GroupBy item.
            /// </summary>
            [RepositoryItem("6e642d51-611e-4be6-9e85-947e1fe91d92")]
            public virtual Ranorex.Container GroupBy
            {
                get
                {
                    return _groupbyInfo.CreateAdapter<Ranorex.Container>(true);
                }
            }

            /// <summary>
            /// The GroupBy item info.
            /// </summary>
            [RepositoryItemInfo("6e642d51-611e-4be6-9e85-947e1fe91d92")]
            public virtual RepoItemInfo GroupByInfo
            {
                get
                {
                    return _groupbyInfo;
                }
            }
        }

        /// <summary>
        /// The MenuButtonBarFolder folder.
        /// </summary>
        [RepositoryFolder("43b586d2-d8da-4a3f-87f2-9e22624fca6b")]
        public partial class MenuButtonBarFolder : RepoGenBaseFolder
        {
            RepoItemInfo _tab_viewInfo;
            RepoItemInfo _tab_homeInfo;

            /// <summary>
            /// Creates a new MenuButtonBar  folder.
            /// </summary>
            public MenuButtonBarFolder(RepoGenBaseFolder parentFolder) :
                    base("MenuButtonBar", ".//tabpagelist[@name='Ribbon Tabs']", parentFolder, 30000, null, false, "43b586d2-d8da-4a3f-87f2-9e22624fca6b", "")
            {
                _tab_viewInfo = new RepoItemInfo(this, "Tab_View", ".//tabpage[@name='View']", "element", 30000, null, "fe5ae9f3-fad4-4d66-94bc-f9aa1c7c63fc");
                _tab_homeInfo = new RepoItemInfo(this, "Tab_Home", ".//tabpage[@name='Home']", "element", 30000, null, "d1831ef4-5671-4ee2-918c-bfbe366907df");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("43b586d2-d8da-4a3f-87f2-9e22624fca6b")]
            public virtual Ranorex.TabPageList Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.TabPageList>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("43b586d2-d8da-4a3f-87f2-9e22624fca6b")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The Tab_View item.
            /// </summary>
            [RepositoryItem("fe5ae9f3-fad4-4d66-94bc-f9aa1c7c63fc")]
            public virtual Ranorex.TabPage Tab_View
            {
                get
                {
                    return _tab_viewInfo.CreateAdapter<Ranorex.TabPage>(true);
                }
            }

            /// <summary>
            /// The Tab_View item info.
            /// </summary>
            [RepositoryItemInfo("fe5ae9f3-fad4-4d66-94bc-f9aa1c7c63fc")]
            public virtual RepoItemInfo Tab_ViewInfo
            {
                get
                {
                    return _tab_viewInfo;
                }
            }

            /// <summary>
            /// The Tab_Home item.
            /// </summary>
            [RepositoryItem("d1831ef4-5671-4ee2-918c-bfbe366907df")]
            public virtual Ranorex.TabPage Tab_Home
            {
                get
                {
                    return _tab_homeInfo.CreateAdapter<Ranorex.TabPage>(true);
                }
            }

            /// <summary>
            /// The Tab_Home item info.
            /// </summary>
            [RepositoryItemInfo("d1831ef4-5671-4ee2-918c-bfbe366907df")]
            public virtual RepoItemInfo Tab_HomeInfo
            {
                get
                {
                    return _tab_homeInfo;
                }
            }
        }

        /// <summary>
        /// The EmailBottomViewFolder folder.
        /// </summary>
        [RepositoryFolder("40412a66-951f-4383-a26b-f700ea829aec")]
        public partial class EmailBottomViewFolder : RepoGenBaseFolder
        {
            RepoItemInfo _emailbodyInfo;
            RepoItemInfo _emailrecipientInfo;

            /// <summary>
            /// Creates a new EmailBottomView  folder.
            /// </summary>
            public EmailBottomViewFolder(RepoGenBaseFolder parentFolder) :
                    base("EmailBottomView", ".//element[@controlid='258']", parentFolder, 30000, null, false, "40412a66-951f-4383-a26b-f700ea829aec", "")
            {
                _emailbodyInfo = new RepoItemInfo(this, "EmailBody", ".//text[@automationid='Body']", "element", 30000, null, "7764e0aa-504a-41bf-bdc0-7bdfc72fd051");
                _emailrecipientInfo = new RepoItemInfo(this, "EmailRecipient", ".//element[@controlid='4295']/text[@accessiblename='To/Cc']", "element", 30000, null, "b2668ca2-ebb1-4ac1-9071-5dfecb15a1a5");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("40412a66-951f-4383-a26b-f700ea829aec")]
            public virtual Ranorex.Unknown Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Unknown>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("40412a66-951f-4383-a26b-f700ea829aec")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The EmailBody item.
            /// </summary>
            [RepositoryItem("7764e0aa-504a-41bf-bdc0-7bdfc72fd051")]
            public virtual Ranorex.Text EmailBody
            {
                get
                {
                    return _emailbodyInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The EmailBody item info.
            /// </summary>
            [RepositoryItemInfo("7764e0aa-504a-41bf-bdc0-7bdfc72fd051")]
            public virtual RepoItemInfo EmailBodyInfo
            {
                get
                {
                    return _emailbodyInfo;
                }
            }

            /// <summary>
            /// The EmailRecipient item.
            /// </summary>
            [RepositoryItem("b2668ca2-ebb1-4ac1-9071-5dfecb15a1a5")]
            public virtual Ranorex.Text EmailRecipient
            {
                get
                {
                    return _emailrecipientInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The EmailRecipient item info.
            /// </summary>
            [RepositoryItemInfo("b2668ca2-ebb1-4ac1-9071-5dfecb15a1a5")]
            public virtual RepoItemInfo EmailRecipientInfo
            {
                get
                {
                    return _emailrecipientInfo;
                }
            }
        }

        /// <summary>
        /// The RibbonFolder folder.
        /// </summary>
        [RepositoryFolder("7bd30b78-158e-4f4a-a099-e1a136a02c72")]
        public partial class RibbonFolder : RepoGenBaseFolder
        {
            RepoItemInfo _newemailInfo;
            RepoItemInfo _buttonreadingpaneInfo;
            RepoItemInfo _menubottomInfo;
            RepoItemInfo _menuoffInfo;

            /// <summary>
            /// Creates a new Ribbon  folder.
            /// </summary>
            public RibbonFolder(RepoGenBaseFolder parentFolder) :
                    base("Ribbon", ".//", parentFolder, 30000, null, false, "7bd30b78-158e-4f4a-a099-e1a136a02c72", "")
            {
                _newemailInfo = new RepoItemInfo(this, "NewEmail", "button[@text='New Email']", "", 30000, null, "5e2e6946-6316-4b9d-b30a-e92fde1e5b3f");
                _buttonreadingpaneInfo = new RepoItemInfo(this, "ButtonReadingPane", "menuitem[@name='Reading Pane']", "", 30000, null, "0e37d025-b342-4171-9907-ee1e95eb39ea");
                _menubottomInfo = new RepoItemInfo(this, "MenuBottom", "menuitem[@name='Bottom']", "", 30000, null, "d86efbef-3b46-40e1-8726-a6fcb3a5068b");
                _menuoffInfo = new RepoItemInfo(this, "MenuOff", "menuitem[@name='Off']", "", 30000, null, "19425e53-e6d6-4603-a857-86b374d63c87");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("7bd30b78-158e-4f4a-a099-e1a136a02c72")]
            public virtual Ranorex.Unknown Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Unknown>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("7bd30b78-158e-4f4a-a099-e1a136a02c72")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The NewEmail item.
            /// </summary>
            [RepositoryItem("5e2e6946-6316-4b9d-b30a-e92fde1e5b3f")]
            public virtual Ranorex.Button NewEmail
            {
                get
                {
                    return _newemailInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The NewEmail item info.
            /// </summary>
            [RepositoryItemInfo("5e2e6946-6316-4b9d-b30a-e92fde1e5b3f")]
            public virtual RepoItemInfo NewEmailInfo
            {
                get
                {
                    return _newemailInfo;
                }
            }

            /// <summary>
            /// The ButtonReadingPane item.
            /// </summary>
            [RepositoryItem("0e37d025-b342-4171-9907-ee1e95eb39ea")]
            public virtual Ranorex.MenuItem ButtonReadingPane
            {
                get
                {
                    return _buttonreadingpaneInfo.CreateAdapter<Ranorex.MenuItem>(true);
                }
            }

            /// <summary>
            /// The ButtonReadingPane item info.
            /// </summary>
            [RepositoryItemInfo("0e37d025-b342-4171-9907-ee1e95eb39ea")]
            public virtual RepoItemInfo ButtonReadingPaneInfo
            {
                get
                {
                    return _buttonreadingpaneInfo;
                }
            }

            /// <summary>
            /// The MenuBottom item.
            /// </summary>
            [RepositoryItem("d86efbef-3b46-40e1-8726-a6fcb3a5068b")]
            public virtual Ranorex.MenuItem MenuBottom
            {
                get
                {
                    return _menubottomInfo.CreateAdapter<Ranorex.MenuItem>(true);
                }
            }

            /// <summary>
            /// The MenuBottom item info.
            /// </summary>
            [RepositoryItemInfo("d86efbef-3b46-40e1-8726-a6fcb3a5068b")]
            public virtual RepoItemInfo MenuBottomInfo
            {
                get
                {
                    return _menubottomInfo;
                }
            }

            /// <summary>
            /// The MenuOff item.
            /// </summary>
            [RepositoryItem("19425e53-e6d6-4603-a857-86b374d63c87")]
            public virtual Ranorex.MenuItem MenuOff
            {
                get
                {
                    return _menuoffInfo.CreateAdapter<Ranorex.MenuItem>(true);
                }
            }

            /// <summary>
            /// The MenuOff item info.
            /// </summary>
            [RepositoryItemInfo("19425e53-e6d6-4603-a857-86b374d63c87")]
            public virtual RepoItemInfo MenuOffInfo
            {
                get
                {
                    return _menuoffInfo;
                }
            }
        }

        /// <summary>
        /// The OutlookMessageAppFolder folder.
        /// </summary>
        [RepositoryFolder("031a66a7-dbdb-4e60-ba7f-9982de8983d6")]
        public partial class OutlookMessageAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _toInfo;
            RepoItemInfo _subjectInfo;
            RepoItemInfo _emailbodyInfo;
            RepoItemInfo _buttonsendInfo;
            RepoItemInfo _buttonclosemessageInfo;
            RepoItemInfo _emailbodyreadmodeInfo;
            RepoItemInfo _buttonreplyInfo;

            /// <summary>
            /// Creates a new OutlookMessage  folder.
            /// </summary>
            public OutlookMessageAppFolder(RepoGenBaseFolder parentFolder) :
                    base("OutlookMessage", "/form[@title~'Message\\ \\(\\w.+\\)\\ ' or @title~'Meeting']", parentFolder, 1000, null, false, "031a66a7-dbdb-4e60-ba7f-9982de8983d6", "")
            {
                _toInfo = new RepoItemInfo(this, "To", ".//element[@controlid='103']/element[@automationid='258']/container[@caption='']/element/text[@accessiblename='To']", "element", 30000, null, "385f88d9-6996-4046-baed-7db26784d511");
                _subjectInfo = new RepoItemInfo(this, "Subject", ".//element[@controlid='103']//element/text[@accessiblename>'Subject']", "element", 30000, null, "b4af8be6-ca5e-4da8-a44f-d58332066992");
                _emailbodyInfo = new RepoItemInfo(this, "EmailBody", "element[@controlid='103']/element[@controlid='258']/container[@caption='']/element[@controlid='4159']/element[@class='_WwB']", "element", 30000, null, "6d16d56d-cf6c-45c0-864f-ff332cacdf17");
                _buttonsendInfo = new RepoItemInfo(this, "ButtonSend", ".//element[@controlid='103']//button[@text='&Send']", "element", 30000, null, "e462922e-33e0-4971-a049-c931b808e1ad");
                _buttonclosemessageInfo = new RepoItemInfo(this, "ButtonCloseMessage", ".//container[@name='Ribbon']/button[@name='Close']", "element", 10000, null, "58b5ea90-6ef8-43a0-9a84-83f4b7861be1");
                _emailbodyreadmodeInfo = new RepoItemInfo(this, "EmailBodyReadMode", ".//element[@automationid='103']//element[@automationid='4159']//text[@automationid='Body']", "element", 30000, null, "f62a9eba-8bb5-4550-a61c-55e9d1de9198");
                _buttonreplyInfo = new RepoItemInfo(this, "ButtonReply", ".///button[@automationid='Reply']", "element", 30000, null, "d43fa4cb-2151-4d96-89e8-478d135c8413");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("031a66a7-dbdb-4e60-ba7f-9982de8983d6")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("031a66a7-dbdb-4e60-ba7f-9982de8983d6")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The To item.
            /// </summary>
            [RepositoryItem("385f88d9-6996-4046-baed-7db26784d511")]
            public virtual Ranorex.Text To
            {
                get
                {
                    return _toInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The To item info.
            /// </summary>
            [RepositoryItemInfo("385f88d9-6996-4046-baed-7db26784d511")]
            public virtual RepoItemInfo ToInfo
            {
                get
                {
                    return _toInfo;
                }
            }

            /// <summary>
            /// The Subject item.
            /// </summary>
            [RepositoryItem("b4af8be6-ca5e-4da8-a44f-d58332066992")]
            public virtual Ranorex.Text Subject
            {
                get
                {
                    return _subjectInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The Subject item info.
            /// </summary>
            [RepositoryItemInfo("b4af8be6-ca5e-4da8-a44f-d58332066992")]
            public virtual RepoItemInfo SubjectInfo
            {
                get
                {
                    return _subjectInfo;
                }
            }

            /// <summary>
            /// The EmailBody item.
            /// </summary>
            [RepositoryItem("6d16d56d-cf6c-45c0-864f-ff332cacdf17")]
            public virtual Ranorex.Unknown EmailBody
            {
                get
                {
                    return _emailbodyInfo.CreateAdapter<Ranorex.Unknown>(true);
                }
            }

            /// <summary>
            /// The EmailBody item info.
            /// </summary>
            [RepositoryItemInfo("6d16d56d-cf6c-45c0-864f-ff332cacdf17")]
            public virtual RepoItemInfo EmailBodyInfo
            {
                get
                {
                    return _emailbodyInfo;
                }
            }

            /// <summary>
            /// The ButtonSend item.
            /// </summary>
            [RepositoryItem("e462922e-33e0-4971-a049-c931b808e1ad")]
            public virtual Ranorex.Button ButtonSend
            {
                get
                {
                    return _buttonsendInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The ButtonSend item info.
            /// </summary>
            [RepositoryItemInfo("e462922e-33e0-4971-a049-c931b808e1ad")]
            public virtual RepoItemInfo ButtonSendInfo
            {
                get
                {
                    return _buttonsendInfo;
                }
            }

            /// <summary>
            /// The ButtonCloseMessage item.
            /// </summary>
            [RepositoryItem("58b5ea90-6ef8-43a0-9a84-83f4b7861be1")]
            public virtual Ranorex.Button ButtonCloseMessage
            {
                get
                {
                    return _buttonclosemessageInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The ButtonCloseMessage item info.
            /// </summary>
            [RepositoryItemInfo("58b5ea90-6ef8-43a0-9a84-83f4b7861be1")]
            public virtual RepoItemInfo ButtonCloseMessageInfo
            {
                get
                {
                    return _buttonclosemessageInfo;
                }
            }

            /// <summary>
            /// The EmailBodyReadMode item.
            /// </summary>
            [RepositoryItem("f62a9eba-8bb5-4550-a61c-55e9d1de9198")]
            public virtual Ranorex.Text EmailBodyReadMode
            {
                get
                {
                    return _emailbodyreadmodeInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The EmailBodyReadMode item info.
            /// </summary>
            [RepositoryItemInfo("f62a9eba-8bb5-4550-a61c-55e9d1de9198")]
            public virtual RepoItemInfo EmailBodyReadModeInfo
            {
                get
                {
                    return _emailbodyreadmodeInfo;
                }
            }

            /// <summary>
            /// The ButtonReply item.
            /// </summary>
            [RepositoryItem("d43fa4cb-2151-4d96-89e8-478d135c8413")]
            public virtual Ranorex.Button ButtonReply
            {
                get
                {
                    return _buttonreplyInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The ButtonReply item info.
            /// </summary>
            [RepositoryItemInfo("d43fa4cb-2151-4d96-89e8-478d135c8413")]
            public virtual RepoItemInfo ButtonReplyInfo
            {
                get
                {
                    return _buttonreplyInfo;
                }
            }
        }

        /// <summary>
        /// The OfficeWarnAppFolder folder.
        /// </summary>
        [RepositoryFolder("d6f30d71-e034-4abd-a833-0ac2242cdbd4")]
        public partial class OfficeWarnAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _buttonnoInfo;
            RepoItemInfo _buttondonotsaveInfo;

            /// <summary>
            /// Creates a new OfficeWarn  folder.
            /// </summary>
            public OfficeWarnAppFolder(RepoGenBaseFolder parentFolder) :
                    base("OfficeWarn", "/form[@title>'Microsoft']", parentFolder, 1000, null, false, "d6f30d71-e034-4abd-a833-0ac2242cdbd4", "")
            {
                _buttonnoInfo = new RepoItemInfo(this, "ButtonNo", ".//button[@text='&No']", "element", 10000, null, "5783b38c-5453-40eb-a1d7-a413cfc33ed7");
                _buttondonotsaveInfo = new RepoItemInfo(this, "ButtonDoNotSave", ".//button[@text='Don''t Save']", "element", 5000, null, "a540cc55-9fe4-4bf9-88e4-da00e0d8619b");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("d6f30d71-e034-4abd-a833-0ac2242cdbd4")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("d6f30d71-e034-4abd-a833-0ac2242cdbd4")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The ButtonNo item.
            /// </summary>
            [RepositoryItem("5783b38c-5453-40eb-a1d7-a413cfc33ed7")]
            public virtual Ranorex.Button ButtonNo
            {
                get
                {
                    return _buttonnoInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The ButtonNo item info.
            /// </summary>
            [RepositoryItemInfo("5783b38c-5453-40eb-a1d7-a413cfc33ed7")]
            public virtual RepoItemInfo ButtonNoInfo
            {
                get
                {
                    return _buttonnoInfo;
                }
            }

            /// <summary>
            /// The ButtonDoNotSave item.
            /// </summary>
            [RepositoryItem("a540cc55-9fe4-4bf9-88e4-da00e0d8619b")]
            public virtual Ranorex.Button ButtonDoNotSave
            {
                get
                {
                    return _buttondonotsaveInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The ButtonDoNotSave item info.
            /// </summary>
            [RepositoryItemInfo("a540cc55-9fe4-4bf9-88e4-da00e0d8619b")]
            public virtual RepoItemInfo ButtonDoNotSaveInfo
            {
                get
                {
                    return _buttondonotsaveInfo;
                }
            }
        }

        /// <summary>
        /// The WordAppFolder folder.
        /// </summary>
        [RepositoryFolder("9268ee68-afc1-4d23-b5e3-2ad953440325")]
        public partial class WordAppFolder : RepoGenBaseFolder
        {
            Ranorex_POCRepositoryFolders.MenuButtonBarFolder1 _menubuttonbar;
            Ranorex_POCRepositoryFolders.InfoMenuBarFolder _infomenubar;
            Ranorex_POCRepositoryFolders.InformationFolder _information;
            Ranorex_POCRepositoryFolders.SaveAsWindowFolder _saveaswindow;
            Ranorex_POCRepositoryFolders.ReplaceWindowFolder _replacewindow;
            Ranorex_POCRepositoryFolders.RibbonFolder1 _ribbon;
            RepoItemInfo _buttonmaximizeInfo;
            RepoItemInfo _newdocumentInfo;
            RepoItemInfo _documentbodyInfo;

            /// <summary>
            /// Creates a new Word  folder.
            /// </summary>
            public WordAppFolder(RepoGenBaseFolder parentFolder) :
                    base("Word", "/form[@processname='WINWORD']", parentFolder, 1000, null, false, "9268ee68-afc1-4d23-b5e3-2ad953440325", "")
            {
                _menubuttonbar = new Ranorex_POCRepositoryFolders.MenuButtonBarFolder1(this);
                _infomenubar = new Ranorex_POCRepositoryFolders.InfoMenuBarFolder(this);
                _information = new Ranorex_POCRepositoryFolders.InformationFolder(this);
                _saveaswindow = new Ranorex_POCRepositoryFolders.SaveAsWindowFolder(this);
                _replacewindow = new Ranorex_POCRepositoryFolders.ReplaceWindowFolder(this);
                _ribbon = new Ranorex_POCRepositoryFolders.RibbonFolder1(this);
                _buttonmaximizeInfo = new RepoItemInfo(this, "ButtonMaximize", ".//button[@name='Maximize']", "element", 10000, null, "2c133388-8e36-4e24-85c8-0b20aed67334");
                _newdocumentInfo = new RepoItemInfo(this, "NewDocument", ".//listitem[@name='Blank document']", "element", 6000, null, "1e6843b6-ea52-4f38-91f4-751a28dfa236");
                _documentbodyInfo = new RepoItemInfo(this, "DocumentBody", ".//text[@automationid='Body']", "element", 30000, null, "284f7463-99ee-40af-8fd7-95cccecfb2bb");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("9268ee68-afc1-4d23-b5e3-2ad953440325")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("9268ee68-afc1-4d23-b5e3-2ad953440325")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The ButtonMaximize item.
            /// </summary>
            [RepositoryItem("2c133388-8e36-4e24-85c8-0b20aed67334")]
            public virtual Ranorex.Button ButtonMaximize
            {
                get
                {
                    return _buttonmaximizeInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The ButtonMaximize item info.
            /// </summary>
            [RepositoryItemInfo("2c133388-8e36-4e24-85c8-0b20aed67334")]
            public virtual RepoItemInfo ButtonMaximizeInfo
            {
                get
                {
                    return _buttonmaximizeInfo;
                }
            }

            /// <summary>
            /// The NewDocument item.
            /// </summary>
            [RepositoryItem("1e6843b6-ea52-4f38-91f4-751a28dfa236")]
            public virtual Ranorex.ListItem NewDocument
            {
                get
                {
                    return _newdocumentInfo.CreateAdapter<Ranorex.ListItem>(true);
                }
            }

            /// <summary>
            /// The NewDocument item info.
            /// </summary>
            [RepositoryItemInfo("1e6843b6-ea52-4f38-91f4-751a28dfa236")]
            public virtual RepoItemInfo NewDocumentInfo
            {
                get
                {
                    return _newdocumentInfo;
                }
            }

            /// <summary>
            /// The DocumentBody item.
            /// </summary>
            [RepositoryItem("284f7463-99ee-40af-8fd7-95cccecfb2bb")]
            public virtual Ranorex.Text DocumentBody
            {
                get
                {
                    return _documentbodyInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The DocumentBody item info.
            /// </summary>
            [RepositoryItemInfo("284f7463-99ee-40af-8fd7-95cccecfb2bb")]
            public virtual RepoItemInfo DocumentBodyInfo
            {
                get
                {
                    return _documentbodyInfo;
                }
            }

            /// <summary>
            /// The MenuButtonBar folder.
            /// </summary>
            [RepositoryFolder("91628d7c-80c3-40ce-b9c2-5d995a2cfff4")]
            public virtual Ranorex_POCRepositoryFolders.MenuButtonBarFolder1 MenuButtonBar
            {
                get { return _menubuttonbar; }
            }

            /// <summary>
            /// The InfoMenuBar folder.
            /// </summary>
            [RepositoryFolder("04d1bd21-33f1-40c9-b500-26f7b18088ce")]
            public virtual Ranorex_POCRepositoryFolders.InfoMenuBarFolder InfoMenuBar
            {
                get { return _infomenubar; }
            }

            /// <summary>
            /// The Information folder.
            /// </summary>
            [RepositoryFolder("386195f4-2ada-4342-bcc3-05b71ae0b5cf")]
            public virtual Ranorex_POCRepositoryFolders.InformationFolder Information
            {
                get { return _information; }
            }

            /// <summary>
            /// The SaveAsWindow folder.
            /// </summary>
            [RepositoryFolder("467390ce-5b43-4c77-b3d2-e636129a01b8")]
            public virtual Ranorex_POCRepositoryFolders.SaveAsWindowFolder SaveAsWindow
            {
                get { return _saveaswindow; }
            }

            /// <summary>
            /// The ReplaceWindow folder.
            /// </summary>
            [RepositoryFolder("2557e28d-7f77-460d-aff3-a8f1ceec8068")]
            public virtual Ranorex_POCRepositoryFolders.ReplaceWindowFolder ReplaceWindow
            {
                get { return _replacewindow; }
            }

            /// <summary>
            /// The Ribbon folder.
            /// </summary>
            [RepositoryFolder("28ccb2b3-1f5c-45eb-9984-2cf2af020970")]
            public virtual Ranorex_POCRepositoryFolders.RibbonFolder1 Ribbon
            {
                get { return _ribbon; }
            }
        }

        /// <summary>
        /// The MenuButtonBarFolder1 folder.
        /// </summary>
        [RepositoryFolder("91628d7c-80c3-40ce-b9c2-5d995a2cfff4")]
        public partial class MenuButtonBarFolder1 : RepoGenBaseFolder
        {
            RepoItemInfo _buttonhomeInfo;
            RepoItemInfo _buttonfileInfo;
            RepoItemInfo _buttoninsertInfo;

            /// <summary>
            /// Creates a new MenuButtonBar  folder.
            /// </summary>
            public MenuButtonBarFolder1(RepoGenBaseFolder parentFolder) :
                    base("MenuButtonBar", ".//*[@caption='Ribbon']", parentFolder, 30000, null, false, "91628d7c-80c3-40ce-b9c2-5d995a2cfff4", "")
            {
                _buttonhomeInfo = new RepoItemInfo(this, "ButtonHome", ".//tabpage[@automationid='TabHome']", "element", 30000, null, "680ecc40-568a-478b-8799-e56acd28e931");
                _buttonfileInfo = new RepoItemInfo(this, "ButtonFile", ".//button[@automationid='FileTabButton']", "element", 30000, null, "d86bd515-dc03-400c-8546-77786e4f3eb4");
                _buttoninsertInfo = new RepoItemInfo(this, "ButtonInsert", ".//tabpage[@automationid='TabInsert']", "element", 30000, null, "a7c40aa8-52c9-4c7e-a0a7-db74629c7b75");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("91628d7c-80c3-40ce-b9c2-5d995a2cfff4")]
            public virtual Ranorex.Unknown Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Unknown>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("91628d7c-80c3-40ce-b9c2-5d995a2cfff4")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The ButtonHome item.
            /// </summary>
            [RepositoryItem("680ecc40-568a-478b-8799-e56acd28e931")]
            public virtual Ranorex.TabPage ButtonHome
            {
                get
                {
                    return _buttonhomeInfo.CreateAdapter<Ranorex.TabPage>(true);
                }
            }

            /// <summary>
            /// The ButtonHome item info.
            /// </summary>
            [RepositoryItemInfo("680ecc40-568a-478b-8799-e56acd28e931")]
            public virtual RepoItemInfo ButtonHomeInfo
            {
                get
                {
                    return _buttonhomeInfo;
                }
            }

            /// <summary>
            /// The ButtonFile item.
            /// </summary>
            [RepositoryItem("d86bd515-dc03-400c-8546-77786e4f3eb4")]
            public virtual Ranorex.Button ButtonFile
            {
                get
                {
                    return _buttonfileInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The ButtonFile item info.
            /// </summary>
            [RepositoryItemInfo("d86bd515-dc03-400c-8546-77786e4f3eb4")]
            public virtual RepoItemInfo ButtonFileInfo
            {
                get
                {
                    return _buttonfileInfo;
                }
            }

            /// <summary>
            /// The ButtonInsert item.
            /// </summary>
            [RepositoryItem("a7c40aa8-52c9-4c7e-a0a7-db74629c7b75")]
            public virtual Ranorex.TabPage ButtonInsert
            {
                get
                {
                    return _buttoninsertInfo.CreateAdapter<Ranorex.TabPage>(true);
                }
            }

            /// <summary>
            /// The ButtonInsert item info.
            /// </summary>
            [RepositoryItemInfo("a7c40aa8-52c9-4c7e-a0a7-db74629c7b75")]
            public virtual RepoItemInfo ButtonInsertInfo
            {
                get
                {
                    return _buttoninsertInfo;
                }
            }
        }

        /// <summary>
        /// The InfoMenuBarFolder folder.
        /// </summary>
        [RepositoryFolder("04d1bd21-33f1-40c9-b500-26f7b18088ce")]
        public partial class InfoMenuBarFolder : RepoGenBaseFolder
        {
            RepoItemInfo _menusaveasInfo;
            RepoItemInfo _menuinfoInfo;
            RepoItemInfo _menuhomeInfo;
            RepoItemInfo _menubackInfo;

            /// <summary>
            /// Creates a new InfoMenuBar  folder.
            /// </summary>
            public InfoMenuBarFolder(RepoGenBaseFolder parentFolder) :
                    base("InfoMenuBar", ".///*[@automationid='NavBarMenu' or @name='File']", parentFolder, 30000, null, false, "04d1bd21-33f1-40c9-b500-26f7b18088ce", "")
            {
                _menusaveasInfo = new RepoItemInfo(this, "MenuSaveAs", ".//*[@name='Save As']", "element", 30000, null, "5081dc63-8ad7-4ba6-9362-32292f506395");
                _menuinfoInfo = new RepoItemInfo(this, "MenuInfo", ".//*[@name='Info']", "element", 30000, null, "e3c3518d-10e2-41f3-aa10-95a953ac4e1c");
                _menuhomeInfo = new RepoItemInfo(this, "MenuHome", ".//*[@name='Home']", "element", 30000, null, "b351f8bb-0790-497a-9019-557f922c5689");
                _menubackInfo = new RepoItemInfo(this, "MenuBack", ".//*[@name='Back']", "element", 30000, null, "7d2b3161-729d-410f-ab9a-024e485482a1");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("04d1bd21-33f1-40c9-b500-26f7b18088ce")]
            public virtual Ranorex.Unknown Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Unknown>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("04d1bd21-33f1-40c9-b500-26f7b18088ce")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The MenuSaveAs item.
            /// </summary>
            [RepositoryItem("5081dc63-8ad7-4ba6-9362-32292f506395")]
            public virtual Ranorex.Unknown MenuSaveAs
            {
                get
                {
                    return _menusaveasInfo.CreateAdapter<Ranorex.Unknown>(true);
                }
            }

            /// <summary>
            /// The MenuSaveAs item info.
            /// </summary>
            [RepositoryItemInfo("5081dc63-8ad7-4ba6-9362-32292f506395")]
            public virtual RepoItemInfo MenuSaveAsInfo
            {
                get
                {
                    return _menusaveasInfo;
                }
            }

            /// <summary>
            /// The MenuInfo item.
            /// </summary>
            [RepositoryItem("e3c3518d-10e2-41f3-aa10-95a953ac4e1c")]
            public virtual Ranorex.Unknown MenuInfo
            {
                get
                {
                    return _menuinfoInfo.CreateAdapter<Ranorex.Unknown>(true);
                }
            }

            /// <summary>
            /// The MenuInfo item info.
            /// </summary>
            [RepositoryItemInfo("e3c3518d-10e2-41f3-aa10-95a953ac4e1c")]
            public virtual RepoItemInfo MenuInfoInfo
            {
                get
                {
                    return _menuinfoInfo;
                }
            }

            /// <summary>
            /// The MenuHome item.
            /// </summary>
            [RepositoryItem("b351f8bb-0790-497a-9019-557f922c5689")]
            public virtual Ranorex.Unknown MenuHome
            {
                get
                {
                    return _menuhomeInfo.CreateAdapter<Ranorex.Unknown>(true);
                }
            }

            /// <summary>
            /// The MenuHome item info.
            /// </summary>
            [RepositoryItemInfo("b351f8bb-0790-497a-9019-557f922c5689")]
            public virtual RepoItemInfo MenuHomeInfo
            {
                get
                {
                    return _menuhomeInfo;
                }
            }

            /// <summary>
            /// The MenuBack item.
            /// </summary>
            [RepositoryItem("7d2b3161-729d-410f-ab9a-024e485482a1")]
            public virtual Ranorex.Unknown MenuBack
            {
                get
                {
                    return _menubackInfo.CreateAdapter<Ranorex.Unknown>(true);
                }
            }

            /// <summary>
            /// The MenuBack item info.
            /// </summary>
            [RepositoryItemInfo("7d2b3161-729d-410f-ab9a-024e485482a1")]
            public virtual RepoItemInfo MenuBackInfo
            {
                get
                {
                    return _menubackInfo;
                }
            }
        }

        /// <summary>
        /// The InformationFolder folder.
        /// </summary>
        [RepositoryFolder("386195f4-2ada-4342-bcc3-05b71ae0b5cf")]
        public partial class InformationFolder : RepoGenBaseFolder
        {
            RepoItemInfo _browsemenubuttonInfo;
            RepoItemInfo _tagInfo;

            /// <summary>
            /// Creates a new Information  folder.
            /// </summary>
            public InformationFolder(RepoGenBaseFolder parentFolder) :
                    base("Information", "", parentFolder, 30000, null, false, "386195f4-2ada-4342-bcc3-05b71ae0b5cf", "")
            {
                _browsemenubuttonInfo = new RepoItemInfo(this, "BrowseMenuButton", ".//button[@name='Browse']", "element", 30000, null, "7ad70015-253b-4ae1-948e-132bf8f11b35");
                _tagInfo = new RepoItemInfo(this, "Tag", ".//container[@name='Properties']/text[@name='Tags' and @iskeyboardfocusable='True']", "element", 30000, null, "3bf26406-be27-48c5-9a40-5ceec67be536");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("386195f4-2ada-4342-bcc3-05b71ae0b5cf")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("386195f4-2ada-4342-bcc3-05b71ae0b5cf")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The BrowseMenuButton item.
            /// </summary>
            [RepositoryItem("7ad70015-253b-4ae1-948e-132bf8f11b35")]
            public virtual Ranorex.Button BrowseMenuButton
            {
                get
                {
                    return _browsemenubuttonInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The BrowseMenuButton item info.
            /// </summary>
            [RepositoryItemInfo("7ad70015-253b-4ae1-948e-132bf8f11b35")]
            public virtual RepoItemInfo BrowseMenuButtonInfo
            {
                get
                {
                    return _browsemenubuttonInfo;
                }
            }

            /// <summary>
            /// The Tag item.
            /// </summary>
            [RepositoryItem("3bf26406-be27-48c5-9a40-5ceec67be536")]
            public virtual Ranorex.Text Tag
            {
                get
                {
                    return _tagInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The Tag item info.
            /// </summary>
            [RepositoryItemInfo("3bf26406-be27-48c5-9a40-5ceec67be536")]
            public virtual RepoItemInfo TagInfo
            {
                get
                {
                    return _tagInfo;
                }
            }
        }

        /// <summary>
        /// The SaveAsWindowFolder folder.
        /// </summary>
        [RepositoryFolder("467390ce-5b43-4c77-b3d2-e636129a01b8")]
        public partial class SaveAsWindowFolder : RepoGenBaseFolder
        {
            RepoItemInfo _filenametextboxInfo;
            RepoItemInfo _savebuttonInfo;

            /// <summary>
            /// Creates a new SaveAsWindow  folder.
            /// </summary>
            public SaveAsWindowFolder(RepoGenBaseFolder parentFolder) :
                    base("SaveAsWindow", ".//form[@title='Save As']", parentFolder, 30000, null, false, "467390ce-5b43-4c77-b3d2-e636129a01b8", "")
            {
                _filenametextboxInfo = new RepoItemInfo(this, "FileNameTextBox", ".//text[@controlid='1001']", "element", 30000, null, "0e4e777c-a0a1-4eb0-b424-ccf24eabc117");
                _savebuttonInfo = new RepoItemInfo(this, "SaveButton", ".//button[@text='&Save']", "element", 30000, null, "5acc2d36-2a4d-4841-8a01-7749be16629d");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("467390ce-5b43-4c77-b3d2-e636129a01b8")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("467390ce-5b43-4c77-b3d2-e636129a01b8")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The FileNameTextBox item.
            /// </summary>
            [RepositoryItem("0e4e777c-a0a1-4eb0-b424-ccf24eabc117")]
            public virtual Ranorex.Text FileNameTextBox
            {
                get
                {
                    return _filenametextboxInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The FileNameTextBox item info.
            /// </summary>
            [RepositoryItemInfo("0e4e777c-a0a1-4eb0-b424-ccf24eabc117")]
            public virtual RepoItemInfo FileNameTextBoxInfo
            {
                get
                {
                    return _filenametextboxInfo;
                }
            }

            /// <summary>
            /// The SaveButton item.
            /// </summary>
            [RepositoryItem("5acc2d36-2a4d-4841-8a01-7749be16629d")]
            public virtual Ranorex.Button SaveButton
            {
                get
                {
                    return _savebuttonInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The SaveButton item info.
            /// </summary>
            [RepositoryItemInfo("5acc2d36-2a4d-4841-8a01-7749be16629d")]
            public virtual RepoItemInfo SaveButtonInfo
            {
                get
                {
                    return _savebuttonInfo;
                }
            }
        }

        /// <summary>
        /// The ReplaceWindowFolder folder.
        /// </summary>
        [RepositoryFolder("2557e28d-7f77-460d-aff3-a8f1ceec8068")]
        public partial class ReplaceWindowFolder : RepoGenBaseFolder
        {
            RepoItemInfo _okbuttonInfo;

            /// <summary>
            /// Creates a new ReplaceWindow  folder.
            /// </summary>
            public ReplaceWindowFolder(RepoGenBaseFolder parentFolder) :
                    base("ReplaceWindow", ".//", parentFolder, 1000, null, false, "2557e28d-7f77-460d-aff3-a8f1ceec8068", "")
            {
                _okbuttonInfo = new RepoItemInfo(this, "OkButton", ".//button[@text='OK']", "text[@caption~'already exists.']/element", 3000, null, "d25e0503-e957-4c6e-85e9-c409570ac1dc");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("2557e28d-7f77-460d-aff3-a8f1ceec8068")]
            public virtual Ranorex.Unknown Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Unknown>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("2557e28d-7f77-460d-aff3-a8f1ceec8068")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The OkButton item.
            /// </summary>
            [RepositoryItem("d25e0503-e957-4c6e-85e9-c409570ac1dc")]
            public virtual Ranorex.Button OkButton
            {
                get
                {
                    return _okbuttonInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The OkButton item info.
            /// </summary>
            [RepositoryItemInfo("d25e0503-e957-4c6e-85e9-c409570ac1dc")]
            public virtual RepoItemInfo OkButtonInfo
            {
                get
                {
                    return _okbuttonInfo;
                }
            }
        }

        /// <summary>
        /// The RibbonFolder1 folder.
        /// </summary>
        [RepositoryFolder("28ccb2b3-1f5c-45eb-9984-2cf2af020970")]
        public partial class RibbonFolder1 : RepoGenBaseFolder
        {
            InsertPictureIconInfoClass _insertpictureiconInfo;
            RepoItemInfo _buttoncloseInfo;

            /// <summary>
            /// Creates a new Ribbon  folder.
            /// </summary>
            public RibbonFolder1(RepoGenBaseFolder parentFolder) :
                    base("Ribbon", ".//container[@name='Ribbon']", parentFolder, 10000, null, false, "28ccb2b3-1f5c-45eb-9984-2cf2af020970", "")
            {
                _insertpictureiconInfo = new InsertPictureIconInfoClass(this);
                _buttoncloseInfo = new RepoItemInfo(this, "ButtonClose", "button[@name='Close']", "", 5000, null, "d3eaebd7-030a-4eb5-8a23-1a0ab142ae59");
            }

            /// <summary>
            /// The InsertPictureIconInfoClass folder.
            /// </summary>
            [RepositoryItemInfo("a468d318-340e-453a-b013-21dfc6704a79")]
            public class InsertPictureIconInfoClass : RepoItemInfo
            {
                /// <summary>
                /// InsertPictureIconInfoClass class constructor.
                /// </summary>
                public InsertPictureIconInfoClass(RepoGenBaseFolder parentFolder)
                    : base(parentFolder, "InsertPictureIcon", ".//menuitem[@automationid='FlyoutAnchorInsertPictures']", 30000, null, "a468d318-340e-453a-b013-21dfc6704a79")
                { }

                /// <summary>
                /// Gets the Screenshot1 item image.
                /// </summary>
                /// <returns>The Screenshot1 image.</returns>
                [RepositoryImage("9b15705e-5106-4281-8fff-f5cb50e9d6b7")]
                public CompressedImage GetScreenshot1()
                {
                    return GetImage("9b15705e-5106-4281-8fff-f5cb50e9d6b7");
                }

                /// <summary>
                /// Gets the Screenshot1 item image.
                /// </summary>
                /// <param name="cropRect">The bounds of the sub-image to return.</param>
                /// <returns>The cropped image.</returns>
                [RepositoryImage("9b15705e-5106-4281-8fff-f5cb50e9d6b7")]
                public CompressedImage GetScreenshot1(System.Drawing.Rectangle cropRect)
                {
                    return GetImage("9b15705e-5106-4281-8fff-f5cb50e9d6b7", cropRect);
                }
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("28ccb2b3-1f5c-45eb-9984-2cf2af020970")]
            public virtual Ranorex.Container Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Container>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("28ccb2b3-1f5c-45eb-9984-2cf2af020970")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The InsertPictureIcon item.
            /// </summary>
            [RepositoryItem("a468d318-340e-453a-b013-21dfc6704a79")]
            public virtual Ranorex.MenuItem InsertPictureIcon
            {
                get
                {
                    return _insertpictureiconInfo.CreateAdapter<Ranorex.MenuItem>(true);
                }
            }

            /// <summary>
            /// The InsertPictureIcon item info.
            /// </summary>
            [RepositoryItemInfo("a468d318-340e-453a-b013-21dfc6704a79")]
            public virtual InsertPictureIconInfoClass InsertPictureIconInfo
            {
                get
                {
                    return _insertpictureiconInfo;
                }
            }

            /// <summary>
            /// The ButtonClose item.
            /// </summary>
            [RepositoryItem("d3eaebd7-030a-4eb5-8a23-1a0ab142ae59")]
            public virtual Ranorex.Button ButtonClose
            {
                get
                {
                    return _buttoncloseInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The ButtonClose item info.
            /// </summary>
            [RepositoryItemInfo("d3eaebd7-030a-4eb5-8a23-1a0ab142ae59")]
            public virtual RepoItemInfo ButtonCloseInfo
            {
                get
                {
                    return _buttoncloseInfo;
                }
            }
        }

    }
#pragma warning restore 0436
}
